Fixed ::  PHP warnings in debug log and the VB builder
elegantthemes/d5-extension-example-modules pull request #29
Opened 2024-10-24 11:01 UTC by robicse11127

# The Issue
## Issue Reference
Fixes: https://github.com/elegantthemes/Divi/issues/40397

## What the issue is
<details>
<summary>🐛 Guideline</summary>

> Explain what the issue is all about.
> Sometimes what is being reported and the problem can be different.
> If this is the case, highlight the difference.

</details>
Fix various PHP warnings and deprecations:
- [ ] [22-Oct-2024 14:06:52 UTC] PHP Deprecated:  Hook divi_visual_builder_assets_before_enqueue_packages is <strong>deprecated</strong> since version 5.0.0-public-alpha.0! Use divi_visual_builder_assets_before_enqueue_scripts instead. in /Users/ayubadiputra/Local Sites/etdev-d5-3ps/app/public/wp-includes/functions.php on line 6085
- [ ] [22-Oct-2024 14:06:52 UTC] PHP Warning:  Dependency &#039;divi-module-library&#039; of script &#039;d5-extension-example-modules-builder-bundle-script&#039; is not registered. in /Users/ayubadiputra/Local Sites/etdev-d5-3ps/app/public/wp-content/themes/Divi/includes/builder-5/server/VisualBuilder/Assets/AssetsUtility.php on line 81
- [ ] [22-Oct-2024 14:06:52 UTC] PHP Warning:  Dependency &#039;divi-vendor-wp-hooks&#039; of script &#039;d5-extension-example-modules-builder-bundle-script&#039; is not registered. in /Users/ayubadiputra/Local Sites/etdev-d5-3ps/app/public/wp-content/themes/Divi/includes/builder-5/server/VisualBuilder/Assets/AssetsUtility.php on line 81

## Replicating issue
<details>
<summary>📝 Guideline</summary>

> List the steps that need to be taken to replicate the issue.
> Provide annotated screenshot, screencast video and/or exported layout
> Export the layout from D4 so it can be checked on both

</details>

## How to Reproduce/Test
- Make sure you have WP and ET debug active, so you can see the warnings in `debug.log` file.
- Install and activate Divi Extension Example Modules plugin. Or you can clone it from [d5-extension-example-modules](https://github.com/elegantthemes/d5-extension-example-modules).
- Open a post/page with VB.
- Check the `debug.log` file and you will find the warnings and deprecations.

## Where does the issue come from

<details>
<summary>🗺 Guideline</summary>

> Give references that you use to reach the conclusion above.
> It can be link to file / commit / PR / discussion, annotated screenshot, screencast, or anything.
> If you are rebuilding D4 features or fixing issues where the expected behavior should be identical with how it works on D4, provide references on how things are working in D4.

</details>

N/A

## When the issue start to happen
<details>
<summary>⌛️ Guideline</summary>

> Conclude when did the issue start to appear.
> Use relative time or relative to certain feature like “during dev beta.x” or “during d5 design implementation”).
> Use git blame.

</details>

`release-public-alpha-2`

## Who to contact regarding the issue
<details>
<summary>👨‍💻👩‍💻 Guideline</summary>

> List people / team that can be contacted for further information about the change that possibly cause the issue.
> This is usually inferred from commit / PR / discussion.
> IMPORTANT: The goal of this is not to put blame on anyone, but to know who to contact to verify the changes and confirm possible regression. This also aims to guide you to look for and understand beyond the issue and ultimately have some transfer knowledge across the team.

</details>

@robicse11127 

## Why the issue happened

<details>
<summary>❓ Guideline</summary>

> You have explained the what, where, when and who.
> Now explain to me why it happened.
> For example: it hasn’t build yet, at the time we have different assumption, it seems like a typo, etc.

</details>

There were basically 2 issues 
- The `StyleDeclarationTrait` was not loaded correctly
- This `divi_visual_builder_assets_before_enqueue_packages` particular hook was deprecated and we needed to use the `et_enqueue_assets`

# The Pull Request
## How this pull request fixes the issue
<details>
<summary>🤔 Guideline</summary>

> Explain how this PR fixes the issue.

</details>

Updated the code accordingly.

## Possible alternate solution
<details>
<summary>🔀 Guideline</summary>

> List other approach (if there’s any) that we could take.
> Explain why those approach isn’t better than the one we are submitting in this PR.
> The goal of this is to be 100% sure that the solution proposed on this PR is the best option that we have right now.

</details>

N/A

## How the PR was verified
<details>
<summary>✅ Guideline</summary>

> Explain how do you verify that this PR addressed the issue.
> For example: attaching before and after screenshots / screencast, adding unit test, etc.

</details>

- There is no issues in debug.log or in the VB while loading

## Testing this PR
<details>
<summary>🔎 Guideline</summary>

> Provide details, clear steps, and precisely what criteria consititues a QA PASS or FAIL.
> If you are referencing `Replicating Issues` on the above, highlight what is the wrong and correct output.
> For example: “in `master`, you’ll see `x` but in this PR’s branch you’ll see `y`”

</details>

- Make sure you have WP and ET debug active, so you can see the warnings in `debug.log` file.
- Install and activate Divi Extension Example Modules plugin. Or you can clone it from [d5-extension-example-modules](https://github.com/elegantthemes/d5-extension-example-modules).
- Open a post/page with VB.
- Check the `debug.log` file and you should not find any issues related to this.
- Also check on VB, there should be no fatal error and warning related to this.

## Changelog copy
Fixed the PHP warnings generated in debug.log file.

## Affected areas
<details>
<summary>🚨 Guideline</summary>

> List the areas of the codebase and/or product that are affected by the changes in this PR. For example:
> * i.e. BB/VB/FE
> * i.e. [Type(s) of modules](https://docs.google.com/spreadsheets/d/1NOg2KNppETydNY_gnd6e3tmXbTxht1L1LB1xEbZFvOg/edit?usp=sharing)
> * i.e. Border Options in the VB

</details>

- VB
- Check debug.log

***

<details>
<summary>📝 NOTES</summary>

1. You don’t need to remove the guideline on the blockquoted area. Just keep it as is.
2. The PR template is intentionally made to be verbose. The goal is to guide developer to take a look at the issue from all angles. This is especially needed when we are considering that there are experienced and new developer in the team. On top of guiding this PR also serves as future references.
3. Good PR description is one that provides all information needed regarding the issue and the solution: A description so good whoever review the PR doesn’t need to dig stuff on their own.

</details>

2024-10-30 09:15 UTC, mohmed98 requested changes
I am still getting 
``` Notice: Undefined property: ET\Builder\Packages\StyleLibrary\Utils\StyleDeclarations::$value in /home/atta/Local Sites/divi-local/app/public/wp-content/plugins/d5-extension-example-modules/modules/ChildModule/ChildModuleTrait/StyleDeclarationTrait.php on line 54```


https://github.com/user-attachments/assets/fab723bf-6928-4a50-9768-83b9ef449613

2024-10-30 09:20 UTC, mohmed98 commented
And where `debug.log` should be located?

2024-10-30 11:53 UTC, robicse11127 commented
@mohmed98 The error you are getting is not related to this PR. Here I have just updated the deprecated the hook name. 

>  Notice: Undefined property: ET\Builder\Packages\StyleLibrary\Utils\StyleDeclarations::$value in /home/atta/Local Sites/divi-local/app/public/wp-content/plugins/d5-extension-example-modules/modules/ChildModule/ChildModuleTrait/StyleDeclarationTrait.php on line 54

And for this :: 

> And where debug.log should be located?

This should be located in under the `wp-content` folder. There there should not be any deprecated related errors.

2024-10-30 20:16 UTC, mohmed98 approved these changes
Cannot test it see [this](https://github.com/elegantthemes/d5-extension-example-modules/pull/29#issuecomment-2448280502), but FE and VB working fine

2024-10-31 14:10 UTC, ayubadiputra approved these changes
LGTM 👍

2024-11-06 22:55 UTC, merged