D5 :: Divi Extension Example Modules :: Non-breaking quick update part 1
elegantthemes/d5-extension-example-modules pull request #31
Opened 2024-10-28 09:31 UTC by robicse11127

# The Issue
## Issue Reference
Fixes: https://github.com/elegantthemes/Divi/issues/40396

## What the issue is
<details>
<summary>🐛 Guideline</summary>

> Explain what the issue is all about.
> Sometimes what is being reported and the problem can be different.
> If this is the case, highlight the difference.

</details>

In readme file we need to remove the information about `module-exceptions.ts` and also need to add the node version in 18.0.0

## Replicating issue
<details>
<summary>📝 Guideline</summary>

> List the steps that need to be taken to replicate the issue.
> Provide annotated screenshot, screencast video and/or exported layout
> Export the layout from D4 so it can be checked on both

</details>

Check the  Repo: [d5-extension-example-modules](https://github.com/elegantthemes/d5-extension-example-modules)
and check the readme file.

## Where does the issue come from

<details>
<summary>🗺 Guideline</summary>

> Give references that you use to reach the conclusion above.
> It can be link to file / commit / PR / discussion, annotated screenshot, screencast, or anything.
> If you are rebuilding D4 features or fixing issues where the expected behavior should be identical with how it works on D4, provide references on how things are working in D4.

</details>

`release-public-alpha-1`

## When the issue start to happen
<details>
<summary>⌛️ Guideline</summary>

> Conclude when did the issue start to appear.
> Use relative time or relative to certain feature like “during dev beta.x” or “during d5 design implementation”).
> Use git blame.

</details>

`release-public-alpha-1`

## Who to contact regarding the issue
<details>
<summary>👨‍💻👩‍💻 Guideline</summary>

> List people / team that can be contacted for further information about the change that possibly cause the issue.
> This is usually inferred from commit / PR / discussion.
> IMPORTANT: The goal of this is not to put blame on anyone, but to know who to contact to verify the changes and confirm possible regression. This also aims to guide you to look for and understand beyond the issue and ultimately have some transfer knowledge across the team.

</details>

@robicse11127 @ayubadiputra 

## Why the issue happened

<details>
<summary>❓ Guideline</summary>

> You have explained the what, where, when and who.
> Now explain to me why it happened.
> For example: it hasn’t build yet, at the time we have different assumption, it seems like a typo, etc.

</details>

- Need to keep the readme.txt file updated with latest information.

# The Pull Request
## How this pull request fixes the issue
<details>
<summary>🤔 Guideline</summary>

> Explain how this PR fixes the issue.

</details>

- Updated the necessary informations.

## Possible alternate solution
<details>
<summary>🔀 Guideline</summary>

> List other approach (if there’s any) that we could take.
> Explain why those approach isn’t better than the one we are submitting in this PR.
> The goal of this is to be 100% sure that the solution proposed on this PR is the best option that we have right now.

</details>

N/A

## How the PR was verified
<details>
<summary>✅ Guideline</summary>

> Explain how do you verify that this PR addressed the issue.
> For example: attaching before and after screenshots / screencast, adding unit test, etc.

</details>

- Check for readme.txt file with new information added.

## Testing this PR
<details>
<summary>🔎 Guideline</summary>

> Provide details, clear steps, and precisely what criteria consititues a QA PASS or FAIL.
> If you are referencing `Replicating Issues` on the above, highlight what is the wrong and correct output.
> For example: “in `master`, you’ll see `x` but in this PR’s branch you’ll see `y`”

</details>

- Check for readme.txt file with new information added.

## Changelog copy
Updated the readme.txt file.

## Affected areas
<details>
<summary>🚨 Guideline</summary>

> List the areas of the codebase and/or product that are affected by the changes in this PR. For example:
> * i.e. BB/VB/FE
> * i.e. [Type(s) of modules](https://docs.google.com/spreadsheets/d/1NOg2KNppETydNY_gnd6e3tmXbTxht1L1LB1xEbZFvOg/edit?usp=sharing)
> * i.e. Border Options in the VB

</details>

- Readme.txt

***

<details>
<summary>📝 NOTES</summary>

1. You don’t need to remove the guideline on the blockquoted area. Just keep it as is.
2. The PR template is intentionally made to be verbose. The goal is to guide developer to take a look at the issue from all angles. This is especially needed when we are considering that there are experienced and new developer in the team. On top of guiding this PR also serves as future references.
3. Good PR description is one that provides all information needed regarding the issue and the solution: A description so good whoever review the PR doesn’t need to dig stuff on their own.

</details>

2024-10-28 21:53 UTC, mohmed98 approved these changes
LGTM :+1: 
Note: the changelog can be enhanced to include a more context like " Updated readme.txt to remove module-exceptions.ts reference and specify Node.js version 18.0.0."

2024-10-29 16:25 UTC, ayubadiputra requested changes

2024-10-29 16:25 UTC, ayubadiputra commented on README.md
> +You need to have **npm** available in your node.js environment. And make sure to use **node version : 18.0.0**
**todo**: This should be "at least" or "minimum" or "18.0.0 and above".

2024-10-29 16:31 UTC, ayubadiputra approved these changes
LGTM 👍

2024-11-06 21:55 UTC, merged