40615 :: D5 :: 3PS :: Transitions :: How To Register Settings/Elements With Transitions Feature
elegantthemes/d5-extension-example-modules pull request #34
Opened 2024-11-13 12:14 UTC by rupakdhiman

Update all D5 modules to adapt to advancedStyles instead of components like CommonStyle, TextStyle, etc..

2024-11-15 08:16 UTC, robicse11127 approved these changes
LGTM !

2024-11-18 15:13 UTC, ayubadiputra requested changes
@rupakdhiman All the things work as expected! Thanks!

But, I have some small feedback. In addition, could you please help to fix some errors below since it's a quick one? 

![Error on child module](https://github.com/user-attachments/assets/133c2f23-d8f2-404e-9f10-518e17980d58)

You just need to call `->value` there as function `->value()`: https://github.com/elegantthemes/d5-extension-example-modules/blob/b61111c0f6d5b2160772ad500196123eb2a1a8ae/modules/ChildModule/ChildModuleTrait/StyleDeclarationTrait.php#L54

Thanks!

2024-11-18 15:13 UTC, ayubadiputra commented on src/components/parent-module/styles.tsx
> +       */}
**todo**: Please fix the indentation.

2024-11-18 15:13 UTC, ayubadiputra commented on src/components/static-module/styles.tsx
> +       */}
**todo**: Please fix the indentation.

2024-11-20 02:37 UTC, ayubadiputra approved these changes
LGTM 👍

2024-12-02 19:20 UTC, Jronk requested changes

2024-12-02 19:20 UTC, Jronk commented on src/components/static-module/styles.tsx
> +      {/**
```suggestion
      {/*
```

2024-12-02 19:20 UTC, Jronk commented on src/components/parent-module/styles.tsx
> +      {/**
```suggestion
      {/*
```

2024-12-02 19:20 UTC, Jronk commented on src/components/child-module/styles.tsx
> +      {/**
```suggestion
      {/*
```

2024-12-02 19:20 UTC, Jronk commented on modules/StaticModule/StaticModuleTrait/ModuleStylesTrait.php
> +					/**
```suggestion
					/*
```

2024-12-02 19:20 UTC, Jronk commented on modules/ParentModule/ParentModuleTrait/ModuleStylesTrait.php
> +					/**
```suggestion
					/*
```

2024-12-02 19:20 UTC, Jronk commented on modules/ChildModule/ChildModuleTrait/ModuleStylesTrait.php
> +					/**
```suggestion
					/*
```

2024-12-02 19:25 UTC, merged